<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260831060342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'records - create table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE records (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, license_plate VARCHAR(20) NOT NULL, entered_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, entry_snapshot_uuid VARCHAR(36) DEFAULT NULL, exited_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, exit_snapshot_uuid VARCHAR(36) DEFAULT NULL, free_until TIMESTAMP(0) WITH TIME ZONE NOT NULL, recognized_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9C9D5846F5AA79D0 ON records (license_plate)');
        $this->addSql('CREATE INDEX IDX_9C9D58465E63B3B1 ON records (entered_at)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9C9D5846F3784A07 ON records (entry_snapshot_uuid)');
        $this->addSql('CREATE INDEX IDX_9C9D5846A82D02A6 ON records (exited_at)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9C9D5846335027B3 ON records (exit_snapshot_uuid)');
        $this->addSql('CREATE INDEX IDX_9C9D584614735233 ON records (free_until)');
        $this->addSql('CREATE INDEX IDX_9C9D58461EE569FB ON records (recognized_user_id)');
        $this->addSql('ALTER TABLE records ADD CONSTRAINT FK_9C9D58461EE569FB FOREIGN KEY (recognized_user_id) REFERENCES users (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE records DROP CONSTRAINT FK_9C9D58461EE569FB');
        $this->addSql('DROP TABLE records');
    }
}
