<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260904053955 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'payments - create table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE payments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, paid_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, amount_excluding_vat NUMERIC(10, 2) NOT NULL, amount_including_vat NUMERIC(10, 2) NOT NULL, vat_rate NUMERIC(10, 2) NOT NULL, currency_code VARCHAR(3) NOT NULL, old_record_free_until TIMESTAMP(0) WITH TIME ZONE NOT NULL, new_record_free_until TIMESTAMP(0) WITH TIME ZONE NOT NULL, record_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65D29B32DEA4208C ON payments (paid_at)');
        $this->addSql('CREATE INDEX IDX_65D29B324DFD750C ON payments (record_id)');
        $this->addSql('ALTER TABLE payments ADD CONSTRAINT FK_65D29B324DFD750C FOREIGN KEY (record_id) REFERENCES records (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE payments DROP CONSTRAINT FK_65D29B324DFD750C');
        $this->addSql('DROP TABLE payments');
    }
}
