<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260921181729 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'events - create table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, action VARCHAR(255) NOT NULL, license_plate VARCHAR(20) NOT NULL, snapshot_uuid VARCHAR(36) DEFAULT NULL, recognized_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5387574A8B8E8428 ON events (created_at)');
        $this->addSql('CREATE INDEX IDX_5387574A47CC8C92 ON events (action)');
        $this->addSql('CREATE INDEX IDX_5387574AF5AA79D0 ON events (license_plate)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5387574AC32FC5DB ON events (snapshot_uuid)');
        $this->addSql('CREATE INDEX IDX_5387574A1EE569FB ON events (recognized_user_id)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574A1EE569FB FOREIGN KEY (recognized_user_id) REFERENCES users (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE events DROP CONSTRAINT FK_5387574A1EE569FB');
        $this->addSql('DROP TABLE events');
    }
}
