<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260826110718 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'vehicles - create table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE vehicles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, license_plate VARCHAR(20) NOT NULL, description TEXT DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1FCE69FA8B8E8428 ON vehicles (created_at)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1FCE69FAF5AA79D0 ON vehicles (license_plate)');
        $this->addSql('CREATE INDEX IDX_1FCE69FA7E3C61F9 ON vehicles (owner_id)');
        $this->addSql('ALTER TABLE vehicles ADD CONSTRAINT FK_1FCE69FA7E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE vehicles DROP CONSTRAINT FK_1FCE69FA7E3C61F9');
        $this->addSql('DROP TABLE vehicles');
    }
}
